name: user

image:
  repository: ghcr.io/side-project-for-sparrows/user-service
  tag: stg
  pullPolicy: Always

replicaCount: 1
containerPort: 8080

postgresql:
  name: user-postgresql
  user: myuser
  password: mypw
  db: mydb
  nodeport: 30001