apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: home-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.129-192.168.1.254   # DHCP와 범위 : 192.168.0.2 ~ 192.168.0.128 이므로 이 밖 해주자