apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}     # 끝. email/server/solvers 같은 ACME 항목 없음
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-cert
  namespace: default
spec:
  secretName: gateway-cert
  dnsNames:
    - unstoppableworm.iptime.org
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned
