apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.name }}-headless
  labels:
    app: {{ .Values.postgresql.name }}
spec:
  clusterIP: None  # Headless Service
  selector:
    app: {{ .Values.postgresql.name }}
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.name }}
  labels:
    app: {{ .Values.postgresql.name }}
spec:
  type: NodePort  # 외부에서 접근할 수 있도록 NodePort 사용
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: {{ .Values.postgresql.nodeport }}  # 30000~32767 범위 내에서 지정 가능
  selector:
    app: {{ .Values.postgresql.name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgresql.name }}
spec:
  serviceName: {{ .Values.postgresql.name }}-headless  # Headless Service 사용
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgresql.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgresql.name }}
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: {{ .Values.postgresql.name }}
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.password }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.db }}
            - name: DB_HOST
              value: {{ .Values.postgresql.name}}
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
        storageClassName: local-path
