apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        log: "true"
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: NEIS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: school-secret
                  key: neis.api-key
            - name: KAKAO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: school-secret
                  key: kakao.api-key