apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: default
spec:
  type: NodePort  # ✅ NodePort로 변경
  selector:
    app: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: {{ .Values.containerPort }}
      nodePort: {{ .Values.nodePort }}
