apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: "true"
    repoURL: https://charts.jetstack.io
    targetRevision: v1.18.2
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true