apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-cr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  source:
    repoURL: https://github.com/Side-Project-for-Sparrows/helmchart
    targetRevision: main
    path: applicationsets/customresource/metallb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true