name: notification

image:
  repository: ghcr.io/side-project-for-sparrows/notification-service
  tag: stg
  pullPolicy: Always

replicaCount: 1
containerPort: 8080

postgresql:
  name: notification-postgresql
  user: myuser
  password: mypw
  db: mydb
  nodeport: 30001