apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:
  fluent-bit.conf: |
    [SERVICE]
      Flush        1
      Daemon       Off
      Log_Level    info
      Parsers_File parsers.conf

    [INPUT]
      Name  tail
      Path  /var/log/containers/*.log
      Tag   kube.*
      Parser  cri
      Exclude_Path /var/log/containers/*fluent-bit*.log
    
    [FILTER]
      Name                kubernetes
      Match               kube.*
      Kube_URL            https://kubernetes.default.svc:443
      Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
      Kube_Tag_Prefix     kube.var.log.containers.
      Merge_Log           Off
      Merge_Log_Key       log_processed
      Keep_Log            Off
    
    [FILTER]
      Name          lua
      Match         kube.*
      script        /fluent-bit/scripts/filter.lua
      call          copy_container_name
    
    [OUTPUT]
      Name            kafka
      Match           kube.*
      Brokers         kafka.default.svc.cluster.local:9092
      Topics          fluent-raw-logs
      Format  json
    
    [OUTPUT]
      Name            stdout
      Match           kube.*
      Format          json_lines

  parsers.conf: |
    [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z