apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-cert
  namespace: default
spec:
  secretName: gateway-cert
  dnsNames:
    - unstoppableworm.iptime.org
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer