name: school

image:
  repository: ghcr.io/side-project-for-sparrows/school-service
  tag: stg
  pullPolicy: Always

replicaCount: 1
containerPort: 8080
nodePort: 30082

postgresql:
  name: school-postgresql
  user: myuser
  password: mypw
  db: mydb
  nodeport: 30002