name: gateway

version: v20250811_1

image:
  repository: ghcr.io/side-project-for-sparrows/gateway-service
  tag: stg
  pullPolicy: Always

replicaCount: 2
containerPort: 7080

ipPool: home-pool
vip: 192.168.0.129

service:
  externalTrafficPolicy: Local

  type: LoadBalancer
  httpPort: 80
  targetHttpPort: 7080

  httpsPort: 443
  targetHttpsPort: 443

env:
  ENV: stg

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

metrics-server:
  namespace: kube-system
  args:
    - --kubelet-insecure-tls
    - --kubelet-preferred-address-types=InternalIP

#ingress:
#  enabled: true
#  className: nginx
#  host: api.sparrow.com
#  path: /(.*)
#  pathType: Prefix
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /$1

#ingress-nginx:
#  controller:
#    service:
#      type: NodePort
#      nodePorts:
#        http: 30080
#        https: 30443
#    admissionWebhooks:
#      enabled: false
#      #patch:
#        #enabled: true