name: search

image:
  repository: ghcr.io/side-project-for-sparrows/search-service
  tag: stg
  pullPolicy: Always

replicaCount: 1
containerPort: 8080

nodePort: 30081

postgresql:
  name: search-postgresql
  user: myuser
  password: mypw
  db: mydb
  nodeport: 30004